[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "NeuroUtils"
version = "0.2.1"
description = "Library for neural network projects organisation"
authors = [{name = "Sebastian Borukało", email = "Ciapserr.info@gmail.com"}]
readme = "README.txt"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Development Status :: 2 - Pre-Alpha",
]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Homepage = "https://github.com/Ciapser/NeuroUtils"

# Include all files in the Assets folder
[tool.setuptools.package-data]
"NeuroUtils" = ["Assets/**/*"]

# Ensure that package data is included
[tool.setuptools]
packages = ["NeuroUtils"]
